spring:
  application:
    name: tasklist
    version: 1.0.0-SNAPSHOT
  profiles:
    active: ${PROFILE:prod}  # Usa "dev" como padrão se não passar nada

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: info
    org.springframework.web: info
    br.com.jtech.tasklist: debug
  file:
    name: ./logs/${spring.application.name}.log

api:
  version: v1
  description: Description here
  url:
    homologation: http://${HOMOLOGATION_SERVER:172.30.1.24}:${HOMOLOGATION_PORT:8081}
    production: ${PRODUCTION_URI:http://${spring.application.name}.jtech.com.br}
