spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tasklistdb;DB_CLOSE_DELAY=-1
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
